added bitrise workflow for publishing the extension. also setup triggers for building commits / PRs / publishing

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -3,7 +3,37 @@ format_version: '4'
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 project_type: other
 workflows:
-  primary:
+  create:
+    steps:
+    - script@1.1.5:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            tfx extension create --manifest-globs "$MANIFEST_GLOBS"
+        title: Create Extension
+    before_run:
+    - _shared
+  publish:
+    steps:
+    - script@1.1.5:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            tfx extension publish --manifest-globs "$MANIFEST_GLOBS" --auth-type pat --token "$VSTS_PERSONAL_ACCESS_TOKEN"
+        title: Publish Extension
+    before_run:
+    - _shared
+  _shared:
     steps:
     - activate-ssh-key@3.1.1:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
@@ -38,19 +68,15 @@ workflows:
         inputs:
         - command: install -g tfx-cli
         title: Install TFS CLI
-    - script@1.1.5:
-        inputs:
-        - content: |-
-            #!/usr/bin/env bash
-            # fail if any commands fails
-            set -e
-            # debug log
-            set -x
-
-            tfx extension create --manifest-globs vss-extension.json
-        title: Create Extension
-    - deploy-to-bitrise-io@1.3.10: {}
 app:
   envs:
   - TASK_DIR_ANDROID_MANIFEST_READ: "$BITRISE_SOURCE_DIR/tasks/AndroidManifestRead"
   - TASK_DIR_GIT_LAST_COMMIT_DATE: "$BITRISE_SOURCE_DIR/tasks/GitLastCommitDate"
+  - MANIFEST_GLOBS: "$BITRISE_SOURCE_DIR/vss-extension.json"
+trigger_map:
+- push_branch: "*"
+  workflow: create
+- pull_request_source_branch: "*"
+  workflow: create
+- tag: v*.*.*
+  workflow: publish
